<?php

namespace App\Models;

use App\Http\Requests\Backend\Asset\AssetTypeRequest;
use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\File;
use Mainul\CustomHelperFunctions\Helpers\CustomHelper;

class AssetType extends Model
{
    use HasFactory, Searchable, SoftDeletes;

    protected $fillable = [
        'name',
        'default_image',
        'height',
        'width',
        'depth',
        'dimension_unit_name',
        'default_price',
        'status',
        'is_digital',
        'total_self',
        'has_kv_space',
    ];

    protected $searchableFields = ['*'];

    protected $table = 'asset_types';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::forceDeleted(function ($model) {
            if (file_exists($model->default_image)) {
                File::delete($model->default_image);
            }
        });
    }

    public static function updateOrCreateAssetType($request, $assetType = null)
    {
        $data = $request->except('default_image');
        if (request()->hasFile('default_image')) {
            $data['default_image'] = CustomHelper::fileUpload($request->file('default_image'), 'asset_type', 'asset_type', 300, 300, $assetType->default_image ?? null);
        }
        return self::updateOrCreate(['id' => $assetType?->id], $data);
    }

    public function assets()
    {
        return $this->hasMany(Asset::class, 'asset_type_id');
    }

}
