<?php

namespace App\Models;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Mainul\CustomHelperFunctions\Helpers\CustomHelper;

class Brand extends Model
{
    use HasFactory;
    use Searchable;
    use SoftDeletes;

    protected $fillable = ['name', 'code', 'description', 'status', 'logo', 'created_by', 'is_common'];

    protected $searchableFields = ['*'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($brand) {

        });
    }

    public static function updateOrCreateBrand($request, $brand = null): self
    {
        $data = $request->validated();
        $data['code'] = strtoupper($data['code']);
        $data['status']    = $request->boolean('status') ? 1 : 0;
        $data['is_common'] = $request->boolean('is_common') ? 1 : 0;
        $data['created_by'] = $brand->created_by ?? auth()->id();

        if ($request->hasFile('logo')) {
            $data['logo'] = CustomHelper::fileUpload(
                $request->file('logo'),
                'brands',
                'brand-logo',
                300,
                300,
                $brand->logo ?? null
            );
        } else {
            $data['logo'] = $brand->logo ?? null;
        }

        return static::updateOrCreate(['id' => $brand?->id], $data);
    }

    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function keyVisuals()
    {
        return $this->belongsToMany(KeyVisual::class);
    }

}
